"""
Builds the updated ECOSETU_MATERIAL_DATASET_PREPARATION.ipynb notebook.
"""

import json
from pathlib import Path

cells = []

# Cell 1: Markdown Title
cells.append({
    'cell_type': 'markdown',
    'metadata': {},
    'source': [
        '# EcoSetu — Genuine XBAT+ WEEE RGB Dataset Acquisition & Quality-Gate Verification\n',
        '\n',
        '> **SIH Problem Statement 26229 — Kabadiwala Connect**  \n',
        '> **Canonical Reference:** `docs/25_SIH_26229_REQUIREMENTS.md`, `docs/27_AI_DATASET_FOUNDATION.md`, `docs/28_AI_MATERIAL_CLASSIFICATION_PIPELINE.md`, `docs/29_AI_DATASET_SOURCES.md`  \n',
        '> **Environment:** Google Colab (CPU / T4 GPU)  \n',
        '> **Scope:** Programmatic acquisition, extraction, validation, mapping, deduplication, YOLO packaging, and Quality Gate verification of the authentic XBAT+ WEEE RGB dataset (Zenodo DOI: `10.5281/zenodo.18022530`).  \n',
        '> **CRITICAL DIRECTIVE:** Prepares the authentic detection dataset in Google Drive. **DOES NOT TRAIN ANY MODEL**.'
    ]
})

# Cell 2: Drive Mount & Storage Check
cells.append({
    'cell_type': 'code',
    'execution_count': None,
    'metadata': {},
    'outputs': [],
    'source': [
        '# 1. Mount Google Drive & Establish Workspace Directories\n',
        'import os\n',
        'import shutil\n',
        'from pathlib import Path\n',
        '\n',
        'try:\n',
        '    from google.colab import drive\n',
        '    drive.mount("/content/drive")\n',
        '    drive_base = Path("/content/drive/MyDrive")\n',
        'except Exception:\n',
        '    print("[WARN] google.colab.drive unavailable; using local directory simulation.")\n',
        '    drive_base = Path("./mock_drive")\n',
        '\n',
        '# Persistent Google Drive Tree\n',
        'DRIVE_ROOT = drive_base / "ECOSETU_AI"\n',
        'DATASETS_DIR = DRIVE_ROOT / "datasets"\n',
        'RAW_DIR = DATASETS_DIR / "raw"\n',
        'PROCESSED_DIR = DATASETS_DIR / "processed"\n',
        'MANIFESTS_DIR = DATASETS_DIR / "manifests"\n',
        'REPORTS_DIR = DATASETS_DIR / "reports"\n',
        'MODELS_DIR = DRIVE_ROOT / "models" / "material-classifier"\n',
        '\n',
        'for p in [RAW_DIR, PROCESSED_DIR, MANIFESTS_DIR, REPORTS_DIR, MODELS_DIR]:\n',
        '    p.mkdir(parents=True, exist_ok=True)\n',
        '\n',
        '# Ephemeral Scratch Directory on Colab VM (Avoids cluttering Drive with intermediate zips)\n',
        'SCRATCH_ROOT = Path("/content/scratch")\n',
        'SCRATCH_DOWNLOADS = SCRATCH_ROOT / "downloads"\n',
        'SCRATCH_STAGING = SCRATCH_ROOT / "staging"\n',
        'for p in [SCRATCH_DOWNLOADS, SCRATCH_STAGING]:\n',
        '    p.mkdir(parents=True, exist_ok=True)\n',
        '\n',
        'total, used, free = shutil.disk_usage(drive_base)\n',
        'print(f"Google Drive Storage: Total={total // (2**30)} GB | Free={free // (2**30)} GB")\n',
        'print(f"[OK] EcoSetu workspace initialized at: {DRIVE_ROOT}")\n',
        'print(f"[OK] Ephemeral scratch initialized at:  {SCRATCH_ROOT}")'
    ]
})

# Cell 3: Dependencies
cells.append({
    'cell_type': 'code',
    'execution_count': None,
    'metadata': {},
    'outputs': [],
    'source': [
        '# 2. Install Required Packages\n',
        '!pip install -q pyyaml pillow requests tqdm\n',
        'print("[OK] Dependencies ready.")'
    ]
})

# Cell 4: Core Validation, Mapping & Deduplication Logic
cells.append({
    'cell_type': 'code',
    'execution_count': None,
    'metadata': {},
    'outputs': [],
    'source': [
        '# 3. Define Canonical Taxonomy, Source Categories & Normalization Engine\n',
        'import re\n',
        'import hashlib\n',
        'from PIL import Image\n',
        '\n',
        '# ECOSETU Canonical 16 Material Categories\n',
        'CANONICAL_CATEGORIES = [\n',
        '    "CRT", "LCD_PANEL", "PCB", "CABLE", "BATTERY", "MOTOR",\n',
        '    "MAGNET_ASSEMBLY", "MIXED_PLASTIC", "MOBILE_PHONE", "LAPTOP",\n',
        '    "MONITOR", "PRINTER", "KEYBOARD_MOUSE", "DESKTOP_COMPUTER",\n',
        '    "TABLET", "OTHER"\n',
        ']\n',
        '\n',
        '# 12 Candidate detection model classes for v0.1.0\n',
        'CANDIDATE_MODEL_CLASSES = [\n',
        '    "BATTERY", "PCB", "CABLE", "MOBILE_PHONE", "LAPTOP", "MONITOR",\n',
        '    "KEYBOARD_MOUSE", "DESKTOP_COMPUTER", "TABLET", "PRINTER", "CRT", "OTHER"\n',
        ']\n',
        '\n',
        '# 4 Excluded classes (zero public e-waste annotations; awaiting field collection)\n',
        'EXCLUDED_INSUFFICIENT_CLASSES = ["MOTOR", "MAGNET_ASSEMBLY", "LCD_PANEL", "MIXED_PLASTIC"]\n',
        '\n',
        '# 15 Canonical categories in XBAT+ v1.0 release metadata (alphabetical index 0..14)\n',
        'XBAT_SOURCE_CLASSES = [\n',
        '    "AlarmClock",      # 0 -> UNMAPPED\n',
        '    "ComputerMouse",   # 1 -> KEYBOARD_MOUSE\n',
        '    "E-Razor",         # 2 -> UNMAPPED\n',
        '    "E-Toothbrush",    # 3 -> UNMAPPED\n',
        '    "FireAlarm",       # 4 -> UNMAPPED\n',
        '    "FlashLight",      # 5 -> UNMAPPED\n',
        '    "GameController",  # 6 -> UNMAPPED\n',
        '    "iPad",            # 7 -> TABLET\n',
        '    "KidToy",          # 8 -> UNMAPPED\n',
        '    "MobilePhone",     # 9 -> MOBILE_PHONE\n',
        '    "NewsRadio",       # 10 -> UNMAPPED\n',
        '    "NightTorch",      # 11 -> UNMAPPED\n',
        '    "PhotoCamera",     # 12 -> UNMAPPED\n',
        '    "RemoteControl",   # 13 -> UNMAPPED\n',
        '    "Thermometer",     # 14 -> UNMAPPED\n',
        ']\n',
        '\n',
        'EXACT_SYNONYM_MAP = {\n',
        '    "computer mouse": "KEYBOARD_MOUSE",\n',
        '    "computermouse": "KEYBOARD_MOUSE",\n',
        '    "mouse": "KEYBOARD_MOUSE",\n',
        '    "keyboard": "KEYBOARD_MOUSE",\n',
        '    "mobile phone": "MOBILE_PHONE",\n',
        '    "mobilephone": "MOBILE_PHONE",\n',
        '    "mobile": "MOBILE_PHONE",\n',
        '    "cell phone": "MOBILE_PHONE",\n',
        '    "smartphone": "MOBILE_PHONE",\n',
        '    "ipad": "TABLET",\n',
        '    "i pad": "TABLET",\n',
        '    "tablet": "TABLET",\n',
        '    "laptop": "LAPTOP",\n',
        '    "monitor": "MONITOR",\n',
        '    "battery": "BATTERY",\n',
        '    "pcb": "PCB",\n',
        '    "cable": "CABLE",\n',
        '    "crt": "CRT",\n',
        '    "printer": "PRINTER",\n',
        '    "desktop": "DESKTOP_COMPUTER",\n',
        '}\n',
        '\n',
        'def normalize_label(label):\n',
        '    if not label:\n',
        '        return ""\n',
        '    cleaned = re.sub(r"([a-z])([A-Z])", r"\\1 \\2", label.strip())\n',
        '    cleaned = cleaned.lower()\n',
        '    cleaned = re.sub(r"[_\\-]+", " ", cleaned)\n',
        '    cleaned = re.sub(r"\\s+", " ", cleaned)\n',
        '    return cleaned.strip()\n',
        '\n',
        'def map_source_class(source_label):\n',
        '    norm = normalize_label(source_label)\n',
        '    return EXACT_SYNONYM_MAP.get(norm, None)\n',
        '\n',
        'def compute_sha256(fpath):\n',
        '    h = hashlib.sha256()\n',
        '    with open(fpath, "rb") as f:\n',
        '        for chunk in iter(lambda: f.read(65536), b""):\n',
        '            h.update(chunk)\n',
        '    return h.hexdigest()\n',
        '\n',
        'def compute_dhash(fpath, hash_size=8):\n',
        '    try:\n',
        '        with Image.open(fpath) as img:\n',
        '            img = img.convert("L").resize((hash_size + 1, hash_size), Image.Resampling.LANCZOS)\n',
        '            pixels = list(img.getdata())\n',
        '            diff = [pixels[r*(hash_size+1)+c] > pixels[r*(hash_size+1)+c+1] for r in range(hash_size) for c in range(hash_size)]\n',
        '            return f"{sum(1 << i for i, v in enumerate(diff) if v):016x}"\n',
        '    except Exception:\n',
        '        return None\n',
        '\n',
        'print("[OK] Core normalization and hashing logic loaded.")'
    ]
})

# Cell 5: Zenodo API Programmatic Query
cells.append({
    'cell_type': 'code',
    'execution_count': None,
    'metadata': {},
    'outputs': [],
    'source': [
        '# 4. Query Official Zenodo API for Record 18022530\n',
        'import json\n',
        'import urllib.request\n',
        '\n',
        'ZENODO_RECORD_ID = "18022530"\n',
        'ZENODO_API_URL = f"https://zenodo.org/api/records/{ZENODO_RECORD_ID}"\n',
        '\n',
        'TARGET_RGB_FILES = {\n',
        '    "raw_XBAT+_v1.0_RGB_train.zip",\n',
        '    "raw_XBAT+_v1.0_RGB_test.zip"\n',
        '}\n',
        '\n',
        'print(f"Connecting to Zenodo API: {ZENODO_API_URL} ...")\n',
        'req = urllib.request.Request(ZENODO_API_URL, headers={"User-Agent": "EcoSetu-Dataset-Pipeline/1.0"})\n',
        'with urllib.request.urlopen(req, timeout=30) as resp:\n',
        '    record_data = json.loads(resp.read().decode("utf-8"))\n',
        '\n',
        'metadata = record_data.get("metadata", {})\n',
        'print(f"Record Title:   {metadata.get(\'title\')}")\n',
        'print(f"DOI:            {record_data.get(\'doi\')}")\n',
        'print(f"License:        {metadata.get(\'license\', {}).get(\'id\', \'CC-BY-4.0\')}")\n',
        '\n',
        'zenodo_rgb_files = {}\n',
        'for f in record_data.get("files", []):\n',
        '    fn = f.get("key")\n',
        '    if fn in TARGET_RGB_FILES:\n',
        '        cs = f.get("checksum", "")\n',
        '        md5 = cs.replace("md5:", "") if cs.startswith("md5:") else cs\n',
        '        zenodo_rgb_files[fn] = {\n',
        '            "size": int(f.get("size", 0)),\n',
        '            "checksum_md5": md5,\n',
        '            "url": f.get("links", {}).get("self")\n',
        '        }\n',
        '\n',
        'print("\\n--- Target XBAT+ RGB Archives Located on Zenodo ---")\n',
        'for fn, info in sorted(zenodo_rgb_files.items()):\n',
        '    print(f"  * {fn:<30} | {info[\'size\'] / (1024*1024):.2f} MB | md5:{info[\'checksum_md5\']}")\n',
        '\n',
        'assert len(zenodo_rgb_files) == 2, f"Expected 2 RGB files on Zenodo, found {len(zenodo_rgb_files)}"'
    ]
})

# Cell 6: Programmatic Download with MD5 Checksum Verification
cells.append({
    'cell_type': 'code',
    'execution_count': None,
    'metadata': {},
    'outputs': [],
    'source': [
        '# 5. Download RGB Archives into Scratch with MD5 Checksum Verification\n',
        'import hashlib\n',
        'from tqdm import tqdm\n',
        '\n',
        'downloaded_archives = {}\n',
        '\n',
        'for fn, info in sorted(zenodo_rgb_files.items()):\n',
        '    dest_path = SCRATCH_DOWNLOADS / fn\n',
        '    url = info["url"]\n',
        '    expected_size = info["size"]\n',
        '    expected_md5 = info["checksum_md5"]\n',
        '    \n',
        '    # Check if already present and valid\n',
        '    if dest_path.exists() and dest_path.stat().st_size == expected_size:\n',
        '        h = hashlib.md5()\n',
        '        with open(dest_path, "rb") as f:\n',
        '            for chunk in iter(lambda: f.read(65536), b""):\n',
        '                h.update(chunk)\n',
        '        if h.hexdigest().lower() == expected_md5.lower():\n',
        '            print(f"[OK] Found cached valid archive: {fn} ({dest_path.stat().st_size / (1024*1024):.2f} MB)")\n',
        '            downloaded_archives[fn] = dest_path\n',
        '            continue\n',
        '    \n',
        '    print(f"\\nDownloading {fn} ({expected_size / (1024*1024):.2f} MB) from Zenodo...")\n',
        '    req = urllib.request.Request(url, headers={"User-Agent": "EcoSetu-Dataset-Pipeline/1.0"})\n',
        '    with urllib.request.urlopen(req, timeout=120) as resp, open(dest_path, "wb") as out:\n',
        '        with tqdm(total=expected_size, unit="B", unit_scale=True, desc=fn) as pbar:\n',
        '            while True:\n',
        '                chunk = resp.read(65536)\n',
        '                if not chunk:\n',
        '                    break\n',
        '                out.write(chunk)\n',
        '                pbar.update(len(chunk))\n',
        '    \n',
        '    # Validate size\n',
        '    actual_size = dest_path.stat().st_size\n',
        '    assert actual_size == expected_size, f"Size mismatch: {actual_size} != {expected_size}"\n',
        '    \n',
        '    # Validate MD5\n',
        '    h = hashlib.md5()\n',
        '    with open(dest_path, "rb") as f:\n',
        '        for chunk in iter(lambda: f.read(65536), b""):\n',
        '            h.update(chunk)\n',
        '    actual_md5 = h.hexdigest().lower()\n',
        '    assert actual_md5 == expected_md5.lower(), f"MD5 mismatch for {fn}: {actual_md5} != {expected_md5}"\n',
        '    \n',
        '    print(f"[OK] Verified {fn} checksum: {actual_md5}")\n',
        '    downloaded_archives[fn] = dest_path\n',
        '\n',
        'print("\\n[OK] All target RGB archives downloaded and verified successfully.")'
    ]
})

# Cell 7: Archive Extraction & Structure Inspection
cells.append({
    'cell_type': 'code',
    'execution_count': None,
    'metadata': {},
    'outputs': [],
    'source': [
        '# 6. Extract Archives to Ephemeral Staging & Inspect Directory Structure\n',
        'import zipfile\n',
        '\n',
        'for fn, arc_path in downloaded_archives.items():\n',
        '    target_stage = SCRATCH_STAGING / fn.replace(".zip", "")\n',
        '    if not target_stage.exists() or not any(target_stage.iterdir()):\n',
        '        print(f"Extracting {fn} to {target_stage}...")\n',
        '        with zipfile.ZipFile(arc_path, "r") as zf:\n',
        '            zf.extractall(target_stage)\n',
        '        print(f"[OK] Extracted {fn}")\n',
        '    else:\n',
        '        print(f"[OK] Staging already extracted for {fn}")\n',
        '\n',
        '# Scan extracted images and labels\n',
        'staged_images = sorted([p for p in SCRATCH_STAGING.rglob("*.*") if p.suffix.lower() in {".jpg", ".jpeg", ".png"}])\n',
        'staged_labels = sorted([p for p in SCRATCH_STAGING.rglob("*.txt") if not p.name.endswith("README.txt")])\n',
        '\n',
        'print(f"\\nTotal Extracted RGB Images: {len(staged_images)}")\n',
        'print(f"Total Extracted YOLO Labels: {len(staged_labels)}")\n',
        'print(f"Sample Image Path: {staged_images[0] if staged_images else \'None\'}")\n',
        'print(f"Sample Label Path: {staged_labels[0] if staged_labels else \'None\'}")'
    ]
})

# Cell 8: Validation, Canonical Mapping, Filtering, Deduplication & Class-Stratified Splitting
cells.append({
    'cell_type': 'code',
    'execution_count': None,
    'metadata': {},
    'outputs': [],
    'source': [
        '# 7. Validate Geometry, Map Classes, Deduplicate & Deterministically Partition (Class-Stratified)\n',
        'import random\n',
        '\n',
        'exclusion_reasons = {\n',
        '    "UNMAPPED_CLASS": 0,\n',
        '    "CORRUPT_IMAGE": 0,\n',
        '    "MISSING_LABEL_FILE": 0,\n',
        '    "INVALID_BBOX": 0,\n',
        '    "EXACT_DUPLICATE": 0,\n',
        '    "PERCEPTUAL_DUPLICATE": 0,\n',
        '}\n',
        '\n',
        'source_class_counts = {}\n',
        'candidate_records = []\n',
        'total_annotations_scanned = 0\n',
        'valid_mapped_annotations = 0\n',
        '\n',
        'for img_path in staged_images:\n',
        '    # Verify readability\n',
        '    try:\n',
        '        with Image.open(img_path) as im:\n',
        '            im.verify()\n',
        '        with Image.open(img_path) as im:\n',
        '            _ = im.size\n',
        '    except Exception:\n',
        '        exclusion_reasons["CORRUPT_IMAGE"] += 1\n',
        '        continue\n',
        '    \n',
        '    # Find parallel or adjacent label file\n',
        '    lbl_path = img_path.with_suffix(".txt")\n',
        '    if not lbl_path.exists() and img_path.parent.name == "images":\n',
        '        lbl_path = img_path.parent.parent / "labels" / f"{img_path.stem}.txt"\n',
        '    \n',
        '    if not lbl_path.exists():\n',
        '        exclusion_reasons["MISSING_LABEL_FILE"] += 1\n',
        '        continue\n',
        '    \n',
        '    with open(lbl_path, "r", encoding="utf-8") as lf:\n',
        '        lines = [ln.strip() for ln in lf if ln.strip()]\n',
        '    \n',
        '    if not lines:\n',
        '        exclusion_reasons["MISSING_LABEL_FILE"] += 1\n',
        '        continue\n',
        '    \n',
        '    mapped_boxes = []\n',
        '    has_invalid_box = False\n',
        '    \n',
        '    for line in lines:\n',
        '        total_annotations_scanned += 1\n',
        '        parts = line.split()\n',
        '        if len(parts) < 5:\n',
        '            has_invalid_box = True\n',
        '            break\n',
        '        try:\n',
        '            src_cls_id = int(parts[0])\n',
        '            xc, yc, w, h = float(parts[1]), float(parts[2]), float(parts[3]), float(parts[4])\n',
        '        except ValueError:\n',
        '            has_invalid_box = True\n',
        '            break\n',
        '        \n',
        '        # Strict bounds verification\n',
        '        if not (0.0 <= xc <= 1.0 and 0.0 <= yc <= 1.0 and 0.0 < w <= 1.0 and 0.0 < h <= 1.0):\n',
        '            has_invalid_box = True\n',
        '            break\n',
        '        \n',
        '        src_name = XBAT_SOURCE_CLASSES[src_cls_id] if 0 <= src_cls_id < len(XBAT_SOURCE_CLASSES) else f"UNKNOWN_{src_cls_id}"\n',
        '        source_class_counts[src_name] = source_class_counts.get(src_name, 0) + 1\n',
        '        \n',
        '        mapped_cat = map_source_class(src_name)\n',
        '        if mapped_cat:\n',
        '            mapped_boxes.append((mapped_cat, xc, yc, w, h))\n',
        '            valid_mapped_annotations += 1\n',
        '    \n',
        '    if has_invalid_box:\n',
        '        exclusion_reasons["INVALID_BBOX"] += 1\n',
        '        continue\n',
        '    \n',
        '    if not mapped_boxes:\n',
        '        # Image contains exclusively unmapped classes (e.g. RemoteControl, AlarmClock)\n',
        '        exclusion_reasons["UNMAPPED_CLASS"] += 1\n',
        '        continue\n',
        '    \n',
        '    candidate_records.append({\n',
        '        "id": img_path.stem,\n',
        '        "path": img_path,\n',
        '        "sha256": compute_sha256(img_path),\n',
        '        "dhash": compute_dhash(img_path),\n',
        '        "boxes": mapped_boxes,\n',
        '    })\n',
        '\n',
        '# Deduplication: Exact SHA-256 and Perceptual dHash\n',
        'seen_sha = set()\n',
        'seen_dhash = {}\n',
        'unique_records = []\n',
        '\n',
        'for rec in candidate_records:\n',
        '    sha = rec["sha256"]\n',
        '    if sha in seen_sha:\n',
        '        exclusion_reasons["EXACT_DUPLICATE"] += 1\n',
        '        continue\n',
        '    seen_sha.add(sha)\n',
        '    \n',
        '    dh = rec["dhash"]\n',
        '    if dh:\n',
        '        dh_int = int(dh, 16)\n',
        '        is_perceptual_dup = False\n',
        '        for prev_dh, prev_id in seen_dhash.items():\n',
        '            prev_int = int(prev_dh, 16)\n',
        '            hamming = bin(dh_int ^ prev_int).count("1")\n',
        '            if hamming <= 4:  # >=94% structural similarity\n',
        '                exclusion_reasons["PERCEPTUAL_DUPLICATE"] += 1\n',
        '                is_perceptual_dup = True\n',
        '                break\n',
        '        if is_perceptual_dup:\n',
        '            continue\n',
        '        seen_dhash[dh] = rec["id"]\n',
        '    \n',
        '    unique_records.append(rec)\n',
        '\n',
        '# Class frequency and dynamic class mapping\n',
        'retained_class_counts = {}\n',
        'images_per_class = {}\n',
        'for rec in unique_records:\n',
        '    seen_in_rec = set()\n',
        '    for cat, _, _, _, _ in rec["boxes"]:\n',
        '        retained_class_counts[cat] = retained_class_counts.get(cat, 0) + 1\n',
        '        seen_in_rec.add(cat)\n',
        '    for cat in seen_in_rec:\n',
        '        images_per_class[cat] = images_per_class.get(cat, 0) + 1\n',
        '\n',
        'retained_classes = sorted(list(retained_class_counts.keys()))\n',
        'class_to_target_idx = {name: idx for idx, name in enumerate(retained_classes)}\n',
        'insufficient_classes = [c for c in CANDIDATE_MODEL_CLASSES if c not in retained_classes]\n',
        '\n',
        '# Genuine Deterministic Class-Aware Stratified 70/20/10 Split\n',
        'records_by_class = {}\n',
        'for rec in unique_records:\n',
        '    primary_cat = rec["boxes"][0][0]\n',
        '    records_by_class.setdefault(primary_cat, []).append(rec)\n',
        '\n',
        'split_map = {"train": [], "val": [], "test": []}\n',
        'for cat in sorted(records_by_class.keys()):\n',
        '    cat_records = records_by_class[cat]\n',
        '    cat_seed = 42 + sum(ord(c) for c in cat)\n',
        '    rng = random.Random(cat_seed)\n',
        '    shuffled_cat = list(cat_records)\n',
        '    shuffled_cat.sort(key=lambda r: r["id"])\n',
        '    rng.shuffle(shuffled_cat)\n',
        '    \n',
        '    n_cat = len(shuffled_cat)\n',
        '    n_cat_train = int(round(n_cat * 0.70))\n',
        '    n_cat_val = int(round(n_cat * 0.20))\n',
        '    n_cat_test = n_cat - n_cat_train - n_cat_val\n',
        '    \n',
        '    if n_cat >= 3:\n',
        '        if n_cat_train < 1: n_cat_train = 1\n',
        '        if n_cat_val < 1: n_cat_val = 1\n',
        '        if n_cat_test < 1:\n',
        '            n_cat_test = 1\n',
        '            if n_cat_train > 1: n_cat_train -= 1\n',
        '    \n',
        '    split_map["train"].extend(shuffled_cat[:n_cat_train])\n',
        '    split_map["val"].extend(shuffled_cat[n_cat_train:n_cat_train + n_cat_val])\n',
        '    split_map["test"].extend(shuffled_cat[n_cat_train + n_cat_val:])\n',
        '\n',
        'n_total = len(unique_records)\n',
        '\n',
        'print("\\n--- Staging & Class-Stratified Split Results ---")\n',
        'print(f"Extracted Images:           {len(staged_images)}")\n',
        'print(f"Extracted Annotations:      {total_annotations_scanned}")\n',
        'print(f"Retained Valid Images:      {n_total}")\n',
        'print(f"Retained Annotations:       {valid_mapped_annotations}")\n',
        'print(f"Excluded Images:            {len(staged_images) - n_total}")\n',
        'print(f"Exclusion Reasons:          {exclusion_reasons}")\n',
        'print(f"Retained Classes ({len(retained_classes)}):     {retained_classes}")\n',
        'print(f"Retained Class Counts:      {retained_class_counts}")\n',
        'print(f"Images Per Class:           {images_per_class}")\n',
        'print(f"Insufficient Classes ({len(insufficient_classes)}): {insufficient_classes}")\n',
        'print(f"Stratified Split Counts:    Train={len(split_map[\'train\'])}, Val={len(split_map[\'val\'])}, Test={len(split_map[\'test\'])}")'
    ]
})

# Cell 9: Write YOLO Dataset, data.yaml, Manifest & Report
cells.append({
    'cell_type': 'code',
    'execution_count': None,
    'metadata': {},
    'outputs': [],
    'source': [
        '# 8. Materialize Final YOLO Dataset, data.yaml, Manifest, and Validation Report\n',
        'import json\n',
        'import yaml\n',
        'from datetime import datetime, timezone\n',
        '\n',
        'DATASET_VERSION = "material-detection-v0.1.0"\n',
        'TARGET_DATASET_DIR = PROCESSED_DIR / DATASET_VERSION\n',
        '\n',
        '# Recreate target directories\n',
        'for split in ["train", "val", "test"]:\n',
        '    (TARGET_DATASET_DIR / "images" / split).mkdir(parents=True, exist_ok=True)\n',
        '    (TARGET_DATASET_DIR / "labels" / split).mkdir(parents=True, exist_ok=True)\n',
        '\n',
        '# Copy images and write normalized YOLO label files\n',
        'split_ann_counts = {"train": 0, "val": 0, "test": 0}\n',
        'for split, recs in split_map.items():\n',
        '    img_out = TARGET_DATASET_DIR / "images" / split\n',
        '    lbl_out = TARGET_DATASET_DIR / "labels" / split\n',
        '    for rec in recs:\n',
        '        src_img = rec["path"]\n',
        '        dest_img = img_out / src_img.name\n',
        '        shutil.copy2(src_img, dest_img)\n',
        '        \n',
        '        dest_lbl = lbl_out / f"{src_img.stem}.txt"\n',
        '        with open(dest_lbl, "w", encoding="utf-8") as lf:\n',
        '            for cat, xc, yc, w, h in rec["boxes"]:\n',
        '                t_idx = class_to_target_idx[cat]\n',
        '                lf.write(f"{t_idx} {xc:.6f} {yc:.6f} {w:.6f} {h:.6f}\\n")\n',
        '                split_ann_counts[split] += 1\n',
        '\n',
        '# Generate data.yaml with ONLY retained classes\n',
        'yaml_config = {\n',
        '    "path": TARGET_DATASET_DIR.resolve().as_posix(),\n',
        '    "train": "images/train",\n',
        '    "val": "images/val",\n',
        '    "test": "images/test",\n',
        '    "nc": len(retained_classes),\n',
        '    "names": {idx: name for idx, name in enumerate(retained_classes)},\n',
        '}\n',
        'yaml_path = TARGET_DATASET_DIR / "data.yaml"\n',
        'with open(yaml_path, "w", encoding="utf-8") as f:\n',
        '    yaml.dump(yaml_config, f, sort_keys=False)\n',
        '\n',
        '# Generate preliminary dataset_manifest.json and validation_report.json\n',
        'manifest = {\n',
        '    "dataset_version": DATASET_VERSION,\n',
        '    "created_at": datetime.now(timezone.utc).isoformat(),\n',
        '    "dataset_type": "object_detection",\n',
        '    "primary_source": {\n',
        '        "name": "XBAT+ WEEE RGB Subset",\n',
        '        "zenodo_record_id": ZENODO_RECORD_ID,\n',
        '        "doi": "10.5281/zenodo.18022530",\n',
        '        "url": "https://zenodo.org/records/18022530",\n',
        '        "license": "CC-BY-4.0",\n',
        '        "archive_files": [\n',
        '            {"filename": "raw_XBAT+_v1.0_RGB_train.zip", "size_bytes": 59670306, "md5": "e5189970528274b87c38e3255ae61236"},\n',
        '            {"filename": "raw_XBAT+_v1.0_RGB_test.zip", "size_bytes": 15789028, "md5": "1e6a5219fd96c1b14a19f8f552354afe"}\n',
        '        ]\n',
        '    },\n',
        '    "source_metrics": {\n',
        '        "extracted_images": len(staged_images),\n',
        '        "extracted_annotations": total_annotations_scanned,\n',
        '        "retained_images": n_total,\n',
        '        "excluded_images": len(staged_images) - n_total,\n',
        '        "exclusion_reasons": exclusion_reasons,\n',
        '        "source_class_distribution": source_class_counts,\n',
        '    },\n',
        '    "supported_classes": retained_classes,\n',
        '    "insufficient_classes": insufficient_classes,\n',
        '    "excluded_classes": EXCLUDED_INSUFFICIENT_CLASSES,\n',
        '    "split_counts": {\n',
        '        "train": len(split_map["train"]),\n',
        '        "val": len(split_map["val"]),\n',
        '        "test": len(split_map["test"]),\n',
        '        "total": n_total,\n',
        '    },\n',
        '    "annotation_counts": {\n',
        '        "train": split_ann_counts["train"],\n',
        '        "val": split_ann_counts["val"],\n',
        '        "test": split_ann_counts["test"],\n',
        '        "total": sum(split_ann_counts.values()),\n',
        '    },\n',
        '    "class_distribution": retained_class_counts,\n',
        '    "images_per_class": images_per_class,\n',
        '    "deduplication": {\n',
        '        "exact_duplicates_removed": exclusion_reasons["EXACT_DUPLICATE"],\n',
        '        "perceptual_duplicates_removed": exclusion_reasons["PERCEPTUAL_DUPLICATE"],\n',
        '    },\n',
        '    "split_seed": 42,\n',
        '    "split_policy": "class_stratified_70_20_10",\n',
        '    "quality_gate_status": "PENDING_VALIDATION",\n',
        '    "location": str(TARGET_DATASET_DIR),\n',
        '}\n',
        'manifest_path = TARGET_DATASET_DIR / "dataset_manifest.json"\n',
        'with open(manifest_path, "w", encoding="utf-8") as f:\n',
        '    json.dump(manifest, f, indent=2)\n',
        '\n',
        'val_report_path = TARGET_DATASET_DIR / "validation_report.json"\n',
        'val_report = {\n',
        '    "generated_at": datetime.now(timezone.utc).isoformat(),\n',
        '    "quality_gate_status": "PENDING_VALIDATION",\n',
        '    "build_status": "PENDING",\n',
        '    "blockers": [],\n',
        '    "metrics": {},\n',
        '}\n',
        'with open(val_report_path, "w", encoding="utf-8") as f:\n',
        '    json.dump(val_report, f, indent=2)\n',
        '\n',
        'print(f"[OK] YOLO layout created at:  {TARGET_DATASET_DIR}")\n',
        'print(f"[OK] data.yaml saved at:       {yaml_path}")\n',
        'print(f"[OK] Manifest saved at:        {manifest_path}")'
    ]
})

# Cell 10: Quality Gate & Validation Report Verification
cells.append({
    'cell_type': 'code',
    'execution_count': None,
    'metadata': {},
    'outputs': [],
    'source': [
        '# 9. Execute Quality Gate & Output Real Measured Statistics (Hardened 26-Point Check)\n',
        'blockers = []\n',
        '\n',
        'train_imgs = sorted(list((TARGET_DATASET_DIR / "images" / "train").glob("*.*")))\n',
        'val_imgs = sorted(list((TARGET_DATASET_DIR / "images" / "val").glob("*.*")))\n',
        'test_imgs = sorted(list((TARGET_DATASET_DIR / "images" / "test").glob("*.*")))\n',
        'final_total_imgs = len(train_imgs) + len(val_imgs) + len(test_imgs)\n',
        '\n',
        'if final_total_imgs == 0:\n',
        '    blockers.append("Total images == 0")\n',
        'if len(train_imgs) == 0:\n',
        '    blockers.append("Train partition is empty")\n',
        'if len(val_imgs) == 0:\n',
        '    blockers.append("Val partition is empty")\n',
        'if len(test_imgs) == 0:\n',
        '    blockers.append("Test partition is empty")\n',
        '\n',
        '# Independent label and image verification across splits\n',
        'actual_class_counts = {c: 0 for c in retained_classes}\n',
        'actual_images_per_class = {c: 0 for c in retained_classes}\n',
        'actual_split_ann_counts = {"train": 0, "val": 0, "test": 0}\n',
        'total_ann_rows = 0\n',
        '\n',
        'for s, s_imgs in [("train", train_imgs), ("val", val_imgs), ("test", test_imgs)]:\n',
        '    for img_p in s_imgs:\n',
        '        # Image readability check\n',
        '        try:\n',
        '            with Image.open(img_p) as im:\n',
        '                im.verify()\n',
        '            with Image.open(img_p) as im:\n',
        '                _ = im.size\n',
        '        except Exception as e:\n',
        '            blockers.append(f"Unreadable image {img_p.name} in {s}: {str(e)}")\n',
        '        \n',
        '        lbl_p = TARGET_DATASET_DIR / "labels" / s / f"{img_p.stem}.txt"\n',
        '        if not lbl_p.exists():\n',
        '            blockers.append(f"Missing label file for {img_p.name} in {s}")\n',
        '            continue\n',
        '        \n',
        '        with open(lbl_p, "r", encoding="utf-8") as lf:\n',
        '            lines = [ln.strip() for ln in lf if ln.strip()]\n',
        '        \n',
        '        if not lines:\n',
        '            blockers.append(f"Empty label file (0 annotations) for {img_p.name} in {s}")\n',
        '            continue\n',
        '        \n',
        '        img_classes_seen = set()\n',
        '        for line in lines:\n',
        '            total_ann_rows += 1\n',
        '            actual_split_ann_counts[s] += 1\n',
        '            parts = line.split()\n',
        '            if len(parts) < 5:\n',
        '                blockers.append(f"Line has < 5 fields in {lbl_p.name}")\n',
        '                continue\n',
        '            try:\n',
        '                c_id = int(parts[0])\n',
        '                xc, yc, w, h = float(parts[1]), float(parts[2]), float(parts[3]), float(parts[4])\n',
        '            except ValueError as ve:\n',
        '                blockers.append(f"Parse error in {lbl_p.name}: {str(ve)}")\n',
        '                continue\n',
        '            \n',
        '            if not (0 <= c_id < len(retained_classes)):\n',
        '                blockers.append(f"Unknown class ID {c_id} in {lbl_p.name}")\n',
        '                continue\n',
        '            if not (0.0 <= xc <= 1.0 and 0.0 <= yc <= 1.0 and 0.0 < w <= 1.0 and 0.0 < h <= 1.0):\n',
        '                blockers.append(f"Out of bounds bbox ({xc},{yc},{w},{h}) in {lbl_p.name}")\n',
        '                continue\n',
        '            \n',
        '            c_name = retained_classes[c_id]\n',
        '            actual_class_counts[c_name] += 1\n',
        '            img_classes_seen.add(c_name)\n',
        '        \n',
        '        for c_name in img_classes_seen:\n',
        '            actual_images_per_class[c_name] += 1\n',
        '\n',
        '# Check zero-annotation classes\n',
        'for cls_name, cnt in actual_class_counts.items():\n',
        '    if cnt == 0:\n',
        '        blockers.append(f"Class {cls_name} has 0 annotations in data.yaml")\n',
        '\n',
        '# Cross-split duplicate leakage check (Exact SHA-256 and Perceptual dHash)\n',
        'train_sha = {compute_sha256(p): p for p in train_imgs}\n',
        'val_sha = {compute_sha256(p): p for p in val_imgs}\n',
        'test_sha = {compute_sha256(p): p for p in test_imgs}\n',
        '\n',
        'leak_tv = set(train_sha.keys()).intersection(set(val_sha.keys()))\n',
        'leak_tt = set(train_sha.keys()).intersection(set(test_sha.keys()))\n',
        'leak_vt = set(val_sha.keys()).intersection(set(test_sha.keys()))\n',
        'if leak_tv or leak_tt or leak_vt:\n',
        '    blockers.append(f"Cross-split duplicate leakage: tv={len(leak_tv)}, tt={len(leak_tt)}, vt={len(leak_vt)}")\n',
        '\n',
        'train_dh = {compute_dhash(p): p for p in train_imgs}\n',
        'val_dh = {compute_dhash(p): p for p in val_imgs}\n',
        'test_dh = {compute_dhash(p): p for p in test_imgs}\n',
        'for dh_t in train_dh:\n',
        '    if not dh_t: continue\n',
        '    for dh_v in val_dh:\n',
        '        if dh_v and bin(int(dh_t, 16) ^ int(dh_v, 16)).count("1") <= 4:\n',
        '            blockers.append("Train/Val perceptual duplicate leakage detected")\n',
        '\n',
        'if not yaml_path.exists():\n',
        '    blockers.append("data.yaml does not exist")\n',
        'if not manifest_path.exists():\n',
        '    blockers.append("dataset_manifest.json does not exist")\n',
        '\n',
        'is_ready = len(blockers) == 0\n',
        'final_gate_status = "READY_FOR_TRAINING" if is_ready else "NOT_READY_FOR_TRAINING"\n',
        '\n',
        '# Update manifest and validation report with ACTUAL evaluated status\n',
        'manifest["quality_gate_status"] = final_gate_status\n',
        'with open(manifest_path, "w", encoding="utf-8") as f:\n',
        '    json.dump(manifest, f, indent=2)\n',
        'with open(MANIFESTS_DIR / f"{DATASET_VERSION}_manifest.json", "w", encoding="utf-8") as f:\n',
        '    json.dump(manifest, f, indent=2)\n',
        '\n',
        'final_bytes = sum(f.stat().st_size for f in TARGET_DATASET_DIR.rglob("*.*") if f.is_file())\n',
        'val_report = {\n',
        '    "generated_at": datetime.now(timezone.utc).isoformat(),\n',
        '    "quality_gate_status": final_gate_status,\n',
        '    "build_status": "SUCCESS" if is_ready else "FAILED",\n',
        '    "blockers": blockers,\n',
        '    "metrics": {\n',
        '        "total_images": final_total_imgs,\n',
        '        "train_count": len(train_imgs),\n',
        '        "val_count": len(val_imgs),\n',
        '        "test_count": len(test_imgs),\n',
        '        "total_annotations": total_ann_rows,\n',
        '        "annotation_counts": actual_split_ann_counts,\n',
        '        "retained_classes": retained_classes,\n',
        '        "class_distribution": actual_class_counts,\n',
        '        "images_per_class": actual_images_per_class,\n',
        '        "exact_duplicates": exclusion_reasons["EXACT_DUPLICATE"],\n',
        '        "perceptual_duplicates": exclusion_reasons["PERCEPTUAL_DUPLICATE"],\n',
        '        "cross_split_leakage": bool(leak_tv or leak_tt or leak_vt),\n',
        '        "final_dataset_bytes": final_bytes,\n',
        '    }\n',
        '}\n',
        'with open(val_report_path, "w", encoding="utf-8") as f:\n',
        '    json.dump(val_report, f, indent=2)\n',
        'with open(REPORTS_DIR / f"{DATASET_VERSION}_validation_report.json", "w", encoding="utf-8") as f:\n',
        '    json.dump(val_report, f, indent=2)\n',
        '\n',
        'print("=" * 64)\n',
        'print("          ECOSETU DATASET BUILD & QUALITY GATE REPORT")\n',
        'print("=" * 64)\n',
        'print(f"QUALITY GATE STATUS:        {final_gate_status}")\n',
        'print(f"DATASET BUILD STATUS:       {\'SUCCESS\' if is_ready else \'FAILED\'}")\n',
        'print(f"TOTAL RETAINED IMAGES:      {final_total_imgs}")\n',
        'print(f"TRAIN / VAL / TEST COUNTS:  {len(train_imgs)} / {len(val_imgs)} / {len(test_imgs)}")\n',
        'print(f"TOTAL ANNOTATIONS:          {total_ann_rows}")\n',
        'print(f"ANNOTATIONS PER SPLIT:      {actual_split_ann_counts}")\n',
        'print(f"SUPPORTED CLASSES:          {retained_classes}")\n',
        'print(f"CLASS DISTRIBUTION (BOXES): {actual_class_counts}")\n',
        'print(f"IMAGES PER CLASS:           {actual_images_per_class}")\n',
        'print(f"INSUFFICIENT CLASSES:       {insufficient_classes}")\n',
        'print(f"EXACT DUPLICATES REMOVED:   {exclusion_reasons[\'EXACT_DUPLICATE\']}")\n',
        'print(f"PERCEPTUAL DUPLICATES:      {exclusion_reasons[\'PERCEPTUAL_DUPLICATE\']}")\n',
        'print(f"CROSS-SPLIT LEAKAGE:        {bool(leak_tv or leak_tt or leak_vt)}")\n',
        'print(f"PHYSICAL DATASET SIZE:      {final_bytes / (1024*1024):.2f} MB")\n',
        'print(f"GOOGLE DRIVE LOCATION:      {TARGET_DATASET_DIR}")\n',
        'print(f"DATASET MANIFEST PATH:      {manifest_path}")\n',
        'print(f"VALIDATION REPORT PATH:     {val_report_path}")\n',
        'if blockers:\n',
        '    print(f"BLOCKERS:                   {blockers}")\n',
        'print("=" * 64)\n',
        'print("\\n--- WORKFLOW COMPLETE: NO MODEL HAS BEEN TRAINED ---")'
    ]
})

nb_data = {
    'cells': cells,
    'metadata': {
        'language_info': {
            'name': 'python'
        }
    },
    'nbformat': 4,
    'nbformat_minor': 2
}

out_path = Path('ai/training/ECOSETU_MATERIAL_DATASET_PREPARATION.ipynb')
with open(out_path, 'w', encoding='utf-8') as f:
    json.dump(nb_data, f, indent=1)

print('Updated notebook written to:', out_path)
