// EcoSetu Backend Constants
// Canonical Reference: docs/00_PROJECT_INDEX.md, docs/04_DATABASE_SCHEMA.md, docs/05_API_SPECIFICATION.md

const ROLES = Object.freeze({
  CITIZEN: 'CITIZEN',
  INFORMAL_COLLECTOR: 'INFORMAL_COLLECTOR',
  RECYCLER: 'RECYCLER',
  ADMIN: 'ADMIN',
});

const USER_STATUS = Object.freeze({
  PENDING_VERIFICATION: 'PENDING_VERIFICATION',
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED',
  DEACTIVATED: 'DEACTIVATED',
});

const EWASTE_CATEGORIES = Object.freeze({
  MOBILE_PHONE: 'MOBILE_PHONE',
  LAPTOP: 'LAPTOP',
  DESKTOP: 'DESKTOP',
  TABLET: 'TABLET',
  MONITOR: 'MONITOR',
  PRINTER: 'PRINTER',
  KEYBOARD_MOUSE: 'KEYBOARD_MOUSE',
  CABLE_CHARGER: 'CABLE_CHARGER',
  BATTERY: 'BATTERY',
  CIRCUIT_BOARD: 'CIRCUIT_BOARD',
  OTHER: 'OTHER',
});

const ITEM_CONDITIONS = Object.freeze({
  WORKING: 'WORKING',
  NOT_WORKING: 'NOT_WORKING',
  DAMAGED: 'DAMAGED',
  UNKNOWN: 'UNKNOWN',
});

const ITEM_STATUS = Object.freeze({
  SUBMITTED: 'SUBMITTED',
  COLLECTED: 'COLLECTED',
  CONSIGNED: 'CONSIGNED',
  RECYCLED: 'RECYCLED',
});

const REQUEST_STATUS = Object.freeze({
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  ACCEPTED: 'ACCEPTED',
  PICKUP_SCHEDULED: 'PICKUP_SCHEDULED',
  PICKED_UP: 'PICKED_UP',
  CANCELLED: 'CANCELLED',
  EXPIRED: 'EXPIRED',
});

const PICKUP_STATUS = Object.freeze({
  SCHEDULED: 'SCHEDULED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
});

const CONSIGNMENT_STATUS = Object.freeze({
  CREATED: 'CREATED',
  IN_TRANSIT: 'IN_TRANSIT',
  DELIVERED: 'DELIVERED',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
});

const RECYCLING_STATUS = Object.freeze({
  RECEIVED: 'RECEIVED',
  PROCESSING: 'PROCESSING',
  COMPLETED: 'COMPLETED',
});

const VERIFICATION_STATUS = Object.freeze({
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
});

const NOTIFICATION_TYPES = Object.freeze({
  REQUEST_ACCEPTED: 'REQUEST_ACCEPTED',
  PICKUP_SCHEDULED: 'PICKUP_SCHEDULED',
  PICKUP_COMPLETED: 'PICKUP_COMPLETED',
  REQUEST_CANCELLED: 'REQUEST_CANCELLED',
  CONSIGNMENT_INCOMING: 'CONSIGNMENT_INCOMING',
  CONSIGNMENT_ACCEPTED: 'CONSIGNMENT_ACCEPTED',
  CONSIGNMENT_REJECTED: 'CONSIGNMENT_REJECTED',
  RECYCLING_COMPLETED: 'RECYCLING_COMPLETED',
  VERIFICATION_APPROVED: 'VERIFICATION_APPROVED',
  VERIFICATION_REJECTED: 'VERIFICATION_REJECTED',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
  ACCOUNT_REACTIVATED: 'ACCOUNT_REACTIVATED',
  ADMIN_MESSAGE: 'ADMIN_MESSAGE',
  HANDOVER_CREATED: 'HANDOVER_CREATED',
  HANDOVER_COLLECTOR_CONFIRMED: 'HANDOVER_COLLECTOR_CONFIRMED',
  HANDOVER_RECYCLER_CONFIRMED: 'HANDOVER_RECYCLER_CONFIRMED',
  HANDOVER_CONFIRMED: 'HANDOVER_CONFIRMED',
  HANDOVER_CANCELLED: 'HANDOVER_CANCELLED',
  TRANSACTION_RECORDED: 'TRANSACTION_RECORDED',
  TRANSACTION_PAYMENT_UPDATED: 'TRANSACTION_PAYMENT_UPDATED',
  TRANSACTION_CANCELLED: 'TRANSACTION_CANCELLED',
});

const ERROR_CODES = Object.freeze({
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
});

const ADDRESS_TYPES = Object.freeze({
  HOME: 'HOME',
  OFFICE: 'OFFICE',
  OTHER: 'OTHER',
});

const MATERIAL_CATEGORIES = Object.freeze({
  CRT: 'CRT',
  LCD_PANEL: 'LCD_PANEL',
  PCB: 'PCB',
  CABLE: 'CABLE',
  BATTERY: 'BATTERY',
  MOTOR: 'MOTOR',
  MAGNET_ASSEMBLY: 'MAGNET_ASSEMBLY',
  MIXED_PLASTIC: 'MIXED_PLASTIC',
  MOBILE_PHONE: 'MOBILE_PHONE',
  LAPTOP: 'LAPTOP',
  MONITOR: 'MONITOR',
  PRINTER: 'PRINTER',
  KEYBOARD_MOUSE: 'KEYBOARD_MOUSE',
  DESKTOP_COMPUTER: 'DESKTOP_COMPUTER',
  TABLET: 'TABLET',
  OTHER: 'OTHER',
});

const MATERIAL_SOURCE_TYPES = Object.freeze({
  HOUSEHOLD: 'HOUSEHOLD',
  COMMERCIAL: 'COMMERCIAL',
  INDUSTRIAL: 'INDUSTRIAL',
  STREET: 'STREET',
  OTHER: 'OTHER',
});

const MATERIAL_LOT_STATUS = Object.freeze({
  DRAFT: 'DRAFT',
  OPEN: 'OPEN',
  QUOTED: 'QUOTED',
  ACCEPTED: 'ACCEPTED',
  HANDOVER_PENDING: 'HANDOVER_PENDING',
  COMPLETED: 'COMPLETED',
});

const PRICE_UNITS = Object.freeze({
  PER_KG: 'PER_KG',
  PER_UNIT: 'PER_UNIT',
  PER_LOT: 'PER_LOT',
});

const PRICE_SOURCES = Object.freeze({
  ADMIN_VERIFIED: 'ADMIN_VERIFIED',
  RECYCLER_OFFER: 'RECYCLER_OFFER',
  IMPORTED_MARKET_DATA: 'IMPORTED_MARKET_DATA',
});

const PRICE_STATUSES = Object.freeze({
  ACTIVE: 'ACTIVE',
  EXPIRED: 'EXPIRED',
  PENDING_REVIEW: 'PENDING_REVIEW',
  REJECTED: 'REJECTED',
});

const PICKUP_AVAILABILITY = Object.freeze({
  AVAILABLE: 'AVAILABLE',
  NOT_AVAILABLE: 'NOT_AVAILABLE',
  UNKNOWN: 'UNKNOWN',
});

const RECYCLER_RATE_STATUS = Object.freeze({
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  EXPIRED: 'EXPIRED',
});

const RECYCLER_AUTHORIZATION_STATUS = Object.freeze({
  AUTHORIZED: 'AUTHORIZED',
  PROVISIONAL: 'PROVISIONAL',
  PENDING: 'PENDING',
  REJECTED: 'REJECTED',
  SUSPENDED: 'SUSPENDED',
  EXPIRED: 'EXPIRED',
  REVOKED: 'REVOKED',
});

const QUOTE_STATUS = Object.freeze({
  SENT: 'SENT',
  VIEWED: 'VIEWED',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
  EXPIRED: 'EXPIRED',
  CANCELLED: 'CANCELLED',
});

const HANDOVER_STATUS = Object.freeze({
  PENDING_COLLECTOR: 'PENDING_COLLECTOR',
  COLLECTOR_CONFIRMED: 'COLLECTOR_CONFIRMED',
  RECYCLER_CONFIRMED: 'RECYCLER_CONFIRMED',
  CONFIRMED: 'CONFIRMED',
  CANCELLED: 'CANCELLED',
});

const AUDIT_ACTIONS = Object.freeze({
  HANDOVER_CREATED: 'HANDOVER_CREATED',
  HANDOVER_COLLECTOR_CONFIRMED: 'HANDOVER_COLLECTOR_CONFIRMED',
  HANDOVER_RECYCLER_CONFIRMED: 'HANDOVER_RECYCLER_CONFIRMED',
  HANDOVER_CONFIRMED: 'HANDOVER_CONFIRMED',
  HANDOVER_PHOTO_ADDED: 'HANDOVER_PHOTO_ADDED',
  HANDOVER_CANCELLED: 'HANDOVER_CANCELLED',
  TRANSACTION_CREATED: 'TRANSACTION_CREATED',
  TRANSACTION_RECORDED: 'TRANSACTION_RECORDED',
  TRANSACTION_PAYMENT_UPDATED: 'TRANSACTION_PAYMENT_UPDATED',
  TRANSACTION_CANCELLED: 'TRANSACTION_CANCELLED',
  RECYCLER_AUTHORIZATION_CHANGED: 'RECYCLER_AUTHORIZATION_CHANGED',
  RECYCLER_PROFILE_UPDATED: 'RECYCLER_PROFILE_UPDATED',
});

const TRANSACTION_TYPE = Object.freeze({
  MATERIAL_SALE: 'MATERIAL_SALE',
});

const PAYMENT_METHOD = Object.freeze({
  CASH: 'CASH',
  UPI_RECORDED: 'UPI_RECORDED',
  BANK_TRANSFER_RECORDED: 'BANK_TRANSFER_RECORDED',
  OTHER: 'OTHER',
});

const PAYMENT_STATUS = Object.freeze({
  PENDING: 'PENDING',
  PAID: 'PAID',
  PARTIALLY_PAID: 'PARTIALLY_PAID',
  FAILED: 'FAILED',
  NOT_APPLICABLE: 'NOT_APPLICABLE',
});

const TRANSACTION_STATUS = Object.freeze({
  DRAFT: 'DRAFT',
  RECORDED: 'RECORDED',
  CANCELLED: 'CANCELLED',
});

const EARNINGS_PERIOD = Object.freeze({
  TODAY: 'TODAY',
  THIS_WEEK: 'THIS_WEEK',
  THIS_MONTH: 'THIS_MONTH',
  LAST_MONTH: 'LAST_MONTH',
  ALL_TIME: 'ALL_TIME',
});

module.exports = {
  ROLES,
  USER_STATUS,
  EWASTE_CATEGORIES,
  ITEM_CONDITIONS,
  ITEM_STATUS,
  REQUEST_STATUS,
  PICKUP_STATUS,
  CONSIGNMENT_STATUS,
  RECYCLING_STATUS,
  VERIFICATION_STATUS,
  NOTIFICATION_TYPES,
  ERROR_CODES,
  ADDRESS_TYPES,
  MATERIAL_CATEGORIES,
  MATERIAL_SOURCE_TYPES,
  MATERIAL_LOT_STATUS,
  PRICE_UNITS,
  PRICE_SOURCES,
  PRICE_STATUSES,
  PICKUP_AVAILABILITY,
  RECYCLER_RATE_STATUS,
  RECYCLER_AUTHORIZATION_STATUS,
  QUOTE_STATUS,
  HANDOVER_STATUS,
  AUDIT_ACTIONS,
  TRANSACTION_TYPE,
  PAYMENT_METHOD,
  PAYMENT_STATUS,
  TRANSACTION_STATUS,
  EARNINGS_PERIOD,
};



